version: '3'

services:
  eureka:
    image: aui-eureka
    restart: always
    ports:
      - "8085:8080"

  db_game:
    image: mariadb:10.10
    restart: always
    environment:
      # MARIADB_ROOT_PASSWORD: "admin"
      # MARIADB_DATABASE: "game"
      # MARIADB_ROOT_HOST: '%'
      # MARIADB_USER: "user2"
      # MARIADB_PASSWORD: "admin"
      - "MYSQL_ROOT_PASSWORD=admin"
      - "MYSQL_DATABASE=game"
      - "MYSQL_ROOT_HOST=%"
    volumes:
      - db_game_data:/var/lib/mysql

  db_developer:
    image: mariadb:10.10
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "admin"
      MARIADB_DATABASE: "developer"
      MARIADB_ROOT_HOST: '%'
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "admin"
    volumes:
      - db_developer_data:/var/lib/mysql

  game-1:
    image: aui-game
    restart: always
    depends_on:
      - db_game
      - eureka
    environment:
      LAB4_DB_RESTART: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "1"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db_game/game"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.mariadb.jdbc.Driver"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MariaDBDialect"
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

  game-2:
    image: aui-game
    restart: always
    depends_on:
      - db_game
      - eureka
    environment:
      LAB4_DB_RESTART: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8080/eureka"
      EUREKA_INSTANCE_INSTANCE_ID: "2"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db_game/game"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.mariadb.jdbc.Driver"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MariaDBDialect"
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"

  developer:
    image: aui-developer
    restart: always
    depends_on:
      - db_developer
      - eureka
    environment:
      LAB4_DB_RESTART: "false"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8080/eureka"
      SPRING_DATASOURCE_URL: "jdbc:mysql://db_developer/developer"
      SPRING_DATASOURCE_DRIVERCLASSNAME: "org.mariadb.jdbc.Driver"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "admin"
      SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MariaDBDialect"
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"


  gateway:
    image: aui-gateway
    restart: always
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://eureka:8080/eureka"
      LAB4_GATEWAY_HOST: "gateway:8080"

  angular:
    image: aui-angular
    restart: always
    depends_on:
      - gateway
    environment:
      API_URL: http://gateway:8080/api
    ports:
      - "8090:80"
volumes:
  db_game_data:
  db_developer_data:

